/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author Tik
 */
public class chonLoTrinh extends javax.swing.JFrame {

    /**
     * Creates new form demoJFrame
     */
    public chonLoTrinh() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel25 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jTextField17 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jPanel26 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jPanel27 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jComboBox5 = new javax.swing.JComboBox<>();
        jComboBox6 = new javax.swing.JComboBox<>();
        jPanel28 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jTextField26 = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(null);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel7.setLayout(null);

        jPanel25.setBackground(new java.awt.Color(255, 255, 255));
        jPanel25.setBorder(javax.swing.BorderFactory.createTitledBorder("Tỉnh"));
        jPanel25.setLayout(null);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_search_24px.png"))); // NOI18N
        jPanel25.add(jButton1);
        jButton1.setBounds(390, 27, 30, 30);

        jLabel16.setText("Từ");
        jPanel25.add(jLabel16);
        jLabel16.setBounds(40, 30, 30, 25);

        jTextField17.setBackground(new java.awt.Color(255, 255, 255));
        jTextField17.setPreferredSize(new java.awt.Dimension(100, 24));
        jTextField17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField17ActionPerformed(evt);
            }
        });
        jPanel25.add(jTextField17);
        jTextField17.setBounds(270, 30, 120, 25);

        jLabel8.setText("đến");
        jPanel25.add(jLabel8);
        jLabel8.setBounds(240, 30, 30, 25);

        jTextField6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel25.add(jTextField6);
        jTextField6.setBounds(70, 30, 120, 25);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_search_24px.png"))); // NOI18N
        jPanel25.add(jButton2);
        jButton2.setBounds(190, 27, 30, 30);

        jPanel7.add(jPanel25);
        jPanel25.setBounds(30, 80, 430, 70);

        jPanel26.setBackground(new java.awt.Color(255, 255, 255));
        jPanel26.setBorder(javax.swing.BorderFactory.createTitledBorder("Tuyến đi"));
        jPanel26.setLayout(null);

        jLabel28.setText("Tuyến");
        jPanel26.add(jLabel28);
        jLabel28.setBounds(20, 30, 40, 25);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bến Thành-Suối Tiên" }));
        jPanel26.add(jComboBox3);
        jComboBox3.setBounds(90, 30, 300, 25);

        jPanel7.add(jPanel26);
        jPanel26.setBounds(30, 160, 430, 70);

        jPanel27.setBackground(new java.awt.Color(255, 255, 255));
        jPanel27.setBorder(javax.swing.BorderFactory.createTitledBorder("Xe"));
        jPanel27.setLayout(null);

        jLabel29.setText("Số xe");
        jPanel27.add(jLabel29);
        jLabel29.setBounds(240, 30, 40, 25);

        jLabel30.setText("Loại xe");
        jPanel27.add(jLabel30);
        jLabel30.setBounds(20, 30, 41, 25);

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "B31-2343" }));
        jPanel27.add(jComboBox5);
        jComboBox5.setBounds(290, 30, 120, 25);

        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Giường nằm" }));
        jPanel27.add(jComboBox6);
        jComboBox6.setBounds(70, 30, 120, 25);

        jPanel7.add(jPanel27);
        jPanel27.setBounds(30, 240, 430, 70);

        jPanel28.setBackground(new java.awt.Color(255, 255, 255));
        jPanel28.setBorder(javax.swing.BorderFactory.createTitledBorder("Chỗ ngồi"));
        jPanel28.setLayout(null);

        jLabel31.setText("Còn lại");
        jPanel28.add(jLabel31);
        jLabel31.setBounds(20, 30, 50, 25);

        jTextField26.setBackground(new java.awt.Color(255, 255, 255));
        jTextField26.setText("20");
        jTextField26.setPreferredSize(new java.awt.Dimension(100, 24));
        jTextField26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField26ActionPerformed(evt);
            }
        });
        jPanel28.add(jTextField26);
        jTextField26.setBounds(70, 30, 30, 25);

        jPanel7.add(jPanel28);
        jPanel28.setBounds(30, 320, 120, 70);

        jLabel34.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel34.setText("CHỌN TUYẾN");
        jPanel7.add(jLabel34);
        jLabel34.setBounds(210, 20, 130, 30);

        jPanel3.add(jPanel7);
        jPanel7.setBounds(0, 0, 510, 420);

        jButton5.setText("Quay lại");
        jPanel3.add(jButton5);
        jButton5.setBounds(270, 440, 90, 40);

        jButton6.setText("Tiếp tục");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton6);
        jButton6.setBounds(370, 440, 100, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 501, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 499, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField17ActionPerformed

    private void jTextField26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField26ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField26ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(chonLoTrinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(chonLoTrinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(chonLoTrinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(chonLoTrinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new chonLoTrinh().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField26;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables
}
