/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author Tik
 */
public class thongTinChuyenDi extends javax.swing.JFrame {

    /**
     * Creates new form demoJFrame
     */
    public thongTinChuyenDi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel24 = new javax.swing.JPanel();
        jTextField5 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jPanel25 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jTextField17 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jPanel26 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jTextField24 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jPanel27 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jTextField25 = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jComboBox5 = new javax.swing.JComboBox<>();
        jPanel28 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jTextField26 = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jTextField27 = new javax.swing.JTextField();
        jPanel29 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jTextField28 = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        jTextField29 = new javax.swing.JTextField();
        jPanel30 = new javax.swing.JPanel();
        jComboBox7 = new javax.swing.JComboBox<>();
        jLabel34 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(null);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel7.setLayout(null);

        jPanel24.setBackground(new java.awt.Color(255, 255, 255));
        jPanel24.setBorder(javax.swing.BorderFactory.createTitledBorder("Tổng"));
        jPanel24.setLayout(null);
        jPanel24.add(jTextField5);
        jTextField5.setBounds(20, 30, 110, 25);

        jLabel4.setText("vnđ");
        jPanel24.add(jLabel4);
        jLabel4.setBounds(140, 30, 30, 25);

        jPanel7.add(jPanel24);
        jPanel24.setBounds(250, 480, 180, 70);

        jPanel25.setBackground(new java.awt.Color(255, 255, 255));
        jPanel25.setBorder(javax.swing.BorderFactory.createTitledBorder("Khách hàng"));
        jPanel25.setLayout(null);

        jLabel16.setText("Tên");
        jPanel25.add(jLabel16);
        jLabel16.setBounds(20, 30, 40, 25);

        jTextField17.setBackground(new java.awt.Color(255, 255, 255));
        jTextField17.setPreferredSize(new java.awt.Dimension(100, 24));
        jTextField17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField17ActionPerformed(evt);
            }
        });
        jPanel25.add(jTextField17);
        jTextField17.setBounds(290, 30, 120, 25);

        jLabel8.setText("Số điện thoại");
        jPanel25.add(jLabel8);
        jLabel8.setBounds(211, 30, 80, 25);

        jTextField6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel25.add(jTextField6);
        jTextField6.setBounds(70, 30, 120, 25);

        jPanel7.add(jPanel25);
        jPanel25.setBounds(30, 80, 430, 70);

        jPanel26.setBackground(new java.awt.Color(255, 255, 255));
        jPanel26.setBorder(javax.swing.BorderFactory.createTitledBorder("Điểm đón"));
        jPanel26.setLayout(null);

        jLabel28.setText("Tỉnh");
        jPanel26.add(jLabel28);
        jLabel28.setBounds(20, 30, 40, 25);

        jTextField24.setBackground(new java.awt.Color(255, 255, 255));
        jTextField24.setPreferredSize(new java.awt.Dimension(100, 24));
        jTextField24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField24ActionPerformed(evt);
            }
        });
        jPanel26.add(jTextField24);
        jTextField24.setBounds(290, 30, 120, 25);

        jLabel10.setText("Địa điểm");
        jPanel26.add(jLabel10);
        jLabel10.setBounds(221, 30, 50, 25);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hồ Chí Minh", "Bình Dương", "Đồng Nai", "Tây Ninh" }));
        jPanel26.add(jComboBox3);
        jComboBox3.setBounds(70, 30, 120, 25);

        jPanel7.add(jPanel26);
        jPanel26.setBounds(30, 160, 430, 70);

        jPanel27.setBackground(new java.awt.Color(255, 255, 255));
        jPanel27.setBorder(javax.swing.BorderFactory.createTitledBorder("Điểm xuống"));
        jPanel27.setLayout(null);

        jLabel29.setText("Tỉnh");
        jPanel27.add(jLabel29);
        jLabel29.setBounds(20, 30, 40, 25);

        jTextField25.setBackground(new java.awt.Color(255, 255, 255));
        jTextField25.setPreferredSize(new java.awt.Dimension(100, 24));
        jTextField25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField25ActionPerformed(evt);
            }
        });
        jPanel27.add(jTextField25);
        jTextField25.setBounds(290, 30, 120, 25);

        jLabel30.setText("Địa điểm");
        jPanel27.add(jLabel30);
        jLabel30.setBounds(221, 30, 50, 25);

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hồ Chí Minh", "Bình Dương", "Đồng Nai", "Tây Ninh" }));
        jPanel27.add(jComboBox5);
        jComboBox5.setBounds(70, 30, 120, 25);

        jPanel7.add(jPanel27);
        jPanel27.setBounds(30, 240, 430, 70);

        jPanel28.setBackground(new java.awt.Color(255, 255, 255));
        jPanel28.setBorder(javax.swing.BorderFactory.createTitledBorder("Lượt đi"));
        jPanel28.setLayout(null);

        jLabel31.setText("Ngày đi");
        jPanel28.add(jLabel31);
        jLabel31.setBounds(20, 30, 50, 25);

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_calendar_16px.png"))); // NOI18N
        jPanel28.add(jLabel17);
        jLabel17.setBounds(160, 28, 30, 30);

        jTextField26.setBackground(new java.awt.Color(255, 255, 255));
        jTextField26.setText("08/09/2020");
        jTextField26.setPreferredSize(new java.awt.Dimension(100, 24));
        jTextField26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField26ActionPerformed(evt);
            }
        });
        jPanel28.add(jTextField26);
        jTextField26.setBounds(70, 30, 110, 25);

        jLabel32.setText("Giờ đi");
        jPanel28.add(jLabel32);
        jLabel32.setBounds(230, 30, 50, 25);

        jTextField27.setBackground(new java.awt.Color(255, 255, 255));
        jTextField27.setPreferredSize(new java.awt.Dimension(100, 24));
        jTextField27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField27ActionPerformed(evt);
            }
        });
        jPanel28.add(jTextField27);
        jTextField27.setBounds(290, 30, 120, 25);

        jPanel7.add(jPanel28);
        jPanel28.setBounds(30, 320, 430, 70);

        jPanel29.setBackground(new java.awt.Color(255, 255, 255));
        jPanel29.setBorder(javax.swing.BorderFactory.createTitledBorder("Lượt về (nếu có)"));
        jPanel29.setLayout(null);

        jLabel18.setText("Ngày về");
        jPanel29.add(jLabel18);
        jLabel18.setBounds(10, 30, 50, 25);

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_calendar_16px.png"))); // NOI18N
        jPanel29.add(jLabel19);
        jLabel19.setBounds(160, 28, 30, 30);

        jTextField28.setBackground(new java.awt.Color(255, 255, 255));
        jTextField28.setPreferredSize(new java.awt.Dimension(100, 24));
        jTextField28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField28ActionPerformed(evt);
            }
        });
        jPanel29.add(jTextField28);
        jTextField28.setBounds(290, 30, 120, 25);

        jLabel33.setText("Giờ về");
        jPanel29.add(jLabel33);
        jLabel33.setBounds(230, 30, 50, 25);

        jTextField29.setBackground(new java.awt.Color(255, 255, 255));
        jTextField29.setText("08/09/2020");
        jTextField29.setPreferredSize(new java.awt.Dimension(100, 24));
        jTextField29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField29ActionPerformed(evt);
            }
        });
        jPanel29.add(jTextField29);
        jTextField29.setBounds(70, 30, 110, 25);

        jPanel7.add(jPanel29);
        jPanel29.setBounds(30, 400, 430, 70);

        jPanel30.setBackground(new java.awt.Color(255, 255, 255));
        jPanel30.setBorder(javax.swing.BorderFactory.createTitledBorder("Thanh toán"));
        jPanel30.setLayout(null);

        jComboBox7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chuyển khoản", "Tiền mặt"}));
        jPanel30.add(jComboBox7);
        jComboBox7.setBounds(20, 30, 120, 25);

        jPanel7.add(jPanel30);
        jPanel30.setBounds(60, 480, 160, 70);

        jLabel34.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel34.setText("ĐẶT VÉ ĐI: BẾN THÀNH-SUỐI TIÊN");
        jPanel7.add(jLabel34);
        jLabel34.setBounds(100, 20, 310, 30);

        jPanel3.add(jPanel7);
        jPanel7.setBounds(0, 0, 510, 570);

        jButton5.setText("Quay lại");
        jPanel3.add(jButton5);
        jButton5.setBounds(260, 580, 90, 40);

        jButton6.setText("Đặt vé");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton6);
        jButton6.setBounds(370, 580, 100, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 501, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 626, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField17ActionPerformed

    private void jTextField24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField24ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField24ActionPerformed

    private void jTextField25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField25ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField25ActionPerformed

    private void jTextField26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField26ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField26ActionPerformed

    private void jTextField27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField27ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField27ActionPerformed

    private void jTextField28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField28ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField28ActionPerformed

    private void jTextField29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField29ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField29ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(thongTinChuyenDi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(thongTinChuyenDi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(thongTinChuyenDi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(thongTinChuyenDi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new thongTinChuyenDi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JComboBox<String> jComboBox7;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField24;
    private javax.swing.JTextField jTextField25;
    private javax.swing.JTextField jTextField26;
    private javax.swing.JTextField jTextField27;
    private javax.swing.JTextField jTextField28;
    private javax.swing.JTextField jTextField29;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables
}
