#!/bin/bash

read -p "press key:" num

mod=0
rev=0

while[$num -gt 0];
do
	let mod=num%10
	let rev=rev*10+mod
	let num/10
done

echo "reverse order %rev"
echo -------------------------------------------
read txt

echo "text trans: `echo $txt | tr -s '[:lower:]' '[:upper:]'`"
